name: Push to Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to Dev VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ~/lux-email-bot-dev
            git fetch origin
            git checkout dev
            git pull origin dev
            npm install
            npm run build
            pm2 restart lux-email-bot-dev || pm2 start npm --name "lux-email-bot-dev" -- start
